package launcher;

import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.ToggleButton;
import javafx.scene.layout.GridPane;

import java.util.ArrayList;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.CheckBox;

public class LauncherController {
	@FXML
	public CheckBox chbPlayer1;
	public CheckBox chbPlayer2;
	public CheckBox chbPlayer3;
	public CheckBox chbPlayer4;
	public CheckBox chbPlayer5;
	public CheckBox chbPlayer6;
	public TextField txtName1;
	public TextField txtName2;
	public TextField txtName3;
	public TextField txtName4;
	public TextField txtName5;
	public TextField txtName6;
	public ComboBox<String> cbColor1;
	public ComboBox<String> cbColor2;
	public ComboBox<String> cbColor3;
	public ComboBox<String> cbColor4;
	public ComboBox<String> cbColor5;
	public ComboBox<String> cbColor6;
	public ComboBox<String> cbRival1;
	public ComboBox<String> cbRival2;
	public ComboBox<String> cbRival3;
	public ComboBox<String> cbRival4;
	public ComboBox<String> cbRival5;
	public ComboBox<String> cbRival6;
	public Button btnStartGame;
	public Button btnExitGame;
	public GridPane gridPane;
	public ToggleButton tbGameBoard4;
	public ToggleButton tbGameBoard6;

	public void initialize() {
		
	}
	
	// Event Listener on CheckBox[#chbSpieler1].onAction
	@FXML
	public void tbOnActionBoard4(ActionEvent event) {
		// TODO Autogenerated
		if(tbGameBoard4.isSelected()) {
			tbGameBoard6.setDisable(true);
			chbPlayer1.setDisable(false);
			
			cbColor1.getItems().add("Gelb");
			cbColor1.getItems().add("Rot");
			cbColor1.getItems().add("Grün");
			cbColor1.getItems().add("Schwarz");
			cbColor1.setValue("Gelb");
			
			cbColor2.getItems().add("Gelb");
			cbColor2.getItems().add("Rot");
			cbColor2.getItems().add("Grün");
			cbColor2.getItems().add("Schwarz");
			cbColor2.setValue("Gelb");
			
			cbColor3.getItems().add("Gelb");
			cbColor3.getItems().add("Rot");
			cbColor3.getItems().add("Grün");
			cbColor3.getItems().add("Schwarz");
			cbColor3.setValue("Gelb");
			
			cbColor4.getItems().add("Gelb");
			cbColor4.getItems().add("Rot");
			cbColor4.getItems().add("Grün");
			cbColor4.getItems().add("Schwarz");
			cbColor4.setValue("Gelb");
			
			cbColor5.getItems().add("Gelb");
			cbColor5.getItems().add("Rot");
			cbColor5.getItems().add("Grün");
			cbColor5.getItems().add("Schwarz");
			cbColor5.setValue("Gelb");
			
			cbColor6.getItems().add("Gelb");
			cbColor6.getItems().add("Rot");
			cbColor6.getItems().add("Grün");
			cbColor6.getItems().add("Schwarz");
			cbColor6.setValue("Gelb");
			
			cbRival1.getItems().add("Mensch");
			cbRival1.getItems().add("Computer");
			cbRival1.setValue("Mensch");
			
			cbRival2.getItems().add("Mensch");
			cbRival2.getItems().add("Computer");
			cbRival2.setValue("Mensch");
			
			cbRival3.getItems().add("Mensch");
			cbRival3.getItems().add("Computer");
			cbRival3.setValue("Mensch");
			
			cbRival4.getItems().add("Mensch");
			cbRival4.getItems().add("Computer");
			cbRival4.setValue("Mensch");
			
			cbRival5.getItems().add("Mensch");
			cbRival5.getItems().add("Computer");
			cbRival5.setValue("Mensch");
			
			cbRival6.getItems().add("Mensch");
			cbRival6.getItems().add("Computer");
			cbRival6.setValue("Mensch");
			
			}
	}
	
	// Event Listener on CheckBox[#chbSpieler1].onAction
	@FXML
	public void tbOnActionBoard6(ActionEvent event) {
		// TODO Autogenerated
		if(tbGameBoard6.isSelected()) {
			tbGameBoard4.setDisable(true);
			chbPlayer1.setDisable(false);
			
			cbColor1.getItems().add("Gelb");
			cbColor1.getItems().add("Rot");
			cbColor1.getItems().add("Grün");
			cbColor1.getItems().add("Schwarz");
			cbColor1.getItems().add("Lila");
			cbColor1.getItems().add("Blau");
			cbColor1.setValue("Gelb");
			
			cbColor2.getItems().add("Gelb");
			cbColor2.getItems().add("Rot");
			cbColor2.getItems().add("Grün");
			cbColor2.getItems().add("Schwarz");
			cbColor2.getItems().add("Lila");
			cbColor2.getItems().add("Blau");
			cbColor2.setValue("Gelb");
			
			cbColor3.getItems().add("Gelb");
			cbColor3.getItems().add("Rot");
			cbColor3.getItems().add("Grün");
			cbColor3.getItems().add("Schwarz");
			cbColor3.getItems().add("Lila");
			cbColor3.getItems().add("Blau");
			cbColor3.setValue("Gelb");
			
			cbColor4.getItems().add("Gelb");
			cbColor4.getItems().add("Rot");
			cbColor4.getItems().add("Grün");
			cbColor4.getItems().add("Schwarz");
			cbColor4.getItems().add("Lila");
			cbColor4.getItems().add("Blau");
			cbColor4.setValue("Gelb");
			
			cbColor5.getItems().add("Gelb");
			cbColor5.getItems().add("Rot");
			cbColor5.getItems().add("Grün");
			cbColor5.getItems().add("Schwarz");
			cbColor5.getItems().add("Lila");
			cbColor5.getItems().add("Blau");
			cbColor5.setValue("Gelb");
			
			cbColor6.getItems().add("Gelb");
			cbColor6.getItems().add("Rot");
			cbColor6.getItems().add("Grün");
			cbColor6.getItems().add("Schwarz");
			cbColor6.getItems().add("Lila");
			cbColor6.getItems().add("Blau");
			cbColor6.setValue("Gelb");
			
			cbRival1.getItems().add("Mensch");
			cbRival1.getItems().add("Computer");
			cbRival1.setValue("Mensch");
			
			cbRival2.getItems().add("Mensch");
			cbRival2.getItems().add("Computer");
			cbRival2.setValue("Mensch");
			
			cbRival3.getItems().add("Mensch");
			cbRival3.getItems().add("Computer");
			cbRival3.setValue("Mensch");
			
			cbRival4.getItems().add("Mensch");
			cbRival4.getItems().add("Computer");
			cbRival4.setValue("Mensch");
			
			cbRival5.getItems().add("Mensch");
			cbRival5.getItems().add("Computer");
			cbRival5.setValue("Mensch");
			
			cbRival6.getItems().add("Mensch");
			cbRival6.getItems().add("Computer");
			cbRival6.setValue("Mensch");
		}
	}
	
	// Event Listener on CheckBox[#chbSpieler1].onAction
	@FXML
	public void chb1OnAction(ActionEvent event) {
		// TODO Autogenerated
		if(chbPlayer1.isSelected()) {
			txtName1.setDisable(false);
			cbColor1.setDisable(false);
			cbRival1.setDisable(false);
			chbPlayer2.setDisable(false);
		} else if (!chbPlayer1.isSelected()) {
			txtName1.setDisable(true);
			cbColor1.setDisable(true);
			cbRival1.setDisable(true);
		}
	}
	// Event Listener on CheckBox[#chbSpieler2].onAction
	@FXML
	public void chb2OnAction(ActionEvent event) {
		// TODO Autogenerated
		if(chbPlayer2.isSelected()) {
			txtName2.setDisable(false);
			cbColor2.setDisable(false);
			cbRival2.setDisable(false);
			chbPlayer3.setDisable(false);
		} else if (!chbPlayer2.isSelected()) {
			txtName2.setDisable(true);
			cbColor2.setDisable(true);
			cbRival2.setDisable(true);
		}
	}
	// Event Listener on CheckBox[#chbSpieler3].onAction
	@FXML
	public void chb3OnAction(ActionEvent event) {
		// TODO Autogenerated
		if(chbPlayer3.isSelected()) {
			txtName3.setDisable(false);
			cbColor3.setDisable(false);
			cbRival3.setDisable(false);
			chbPlayer4.setDisable(false);
		} else if (!chbPlayer3.isSelected()) {
			txtName3.setDisable(true);
			cbColor3.setDisable(true);
			cbRival3.setDisable(true);
		}
	}
	// Event Listener on CheckBox[#chbSpieler4].onAction
	@FXML
	public void chb4OnAction(ActionEvent event) {
		// TODO Autogenerated
		if(chbPlayer4.isSelected()) {
			txtName4.setDisable(false);
			cbColor4.setDisable(false);
			cbRival4.setDisable(false);
			chbPlayer5.setDisable(false);
		} else if (!chbPlayer4.isSelected()) {
			txtName4.setDisable(true);
			cbColor4.setDisable(true);
			cbRival4.setDisable(true);
		}
	}
	// Event Listener on CheckBox[#chbSpieler5].onAction
	@FXML
	public void chb5OnAction(ActionEvent event) {
		// TODO Autogenerated
		if(chbPlayer5.isSelected()) {
			txtName5.setDisable(false);
			cbColor5.setDisable(false);
			cbRival5.setDisable(false);
			chbPlayer6.setDisable(false);
		} else if (!chbPlayer5.isSelected()) {
			txtName5.setDisable(true);
			cbColor5.setDisable(true);
			cbRival5.setDisable(true);
		}
	}
	// Event Listener on CheckBox[#chbSpieler6].onAction
	@FXML
	public void chb6OnAction(ActionEvent event) {
		// TODO Autogenerated
		if(chbPlayer6.isSelected()) {
			txtName6.setDisable(false);
			cbColor6.setDisable(false);
			cbRival6.setDisable(false);
		} else if (!chbPlayer6.isSelected()) {
			txtName6.setDisable(true);
			cbColor6.setDisable(true);
			cbRival6.setDisable(true);
			
		}
	}
	
	
	
	// Event Listener on Button[#btnSpielstarten].onAction
	@FXML
	public void buttonOnActionStart(ActionEvent event) {
		// TODO Autogenerated
		if((chbPlayer1.isSelected() && txtName1.getLength() == 0) || (chbPlayer2.isSelected() && txtName2.getLength() == 0) || (chbPlayer3.isSelected() && txtName3.getLength() == 0) || (chbPlayer4.isSelected() && txtName4.getLength() == 0) || (chbPlayer5.isSelected() && txtName5.getLength() == 0) || (chbPlayer6.isSelected() && txtName6.getLength() == 0)) {
			Alert alert = new Alert(Alert.AlertType.INFORMATION);
			alert.setTitle("Fehlermeldung");
			alert.setContentText("Bitte füllen Sie alle erforderlichen Angaben aus, bevor das Spiel beginnen kann.");
		}
		
	}
	// Event Listener on Button[#btnSpielbeenden].onAction
	@FXML
	public void buttonOnActionExit(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}
}
